### PR TITLE
Add zoe roadmap, update links in zoe/guide/README.md

### PR DESCRIPTION
**Pull request by katelynsills**

### CODE REVIEW

**Comment by katelynsills** [comment]
We can comment them out for now

**Comment by barbaraliau** [comment]
K. I'll do that and then merge this.

**Comment by katelynsills** [comment]
Ok, we might have merge conflicts, I commented out the TODO links I couldn't fill and added a doc about structuring the offer rules.

**Comment by barbaraliau** [comment]
I am putting this comment here for reference. I tried to reply via email but Github rejected it.

> I pushed a quick 'in progress page' so you can keep live links in the future if you wanted, but have them redirect to an `/in-progress` instead so it isn't a 404.

**Pull request merged**
