### PR TITLE
docs: Add follow command to Agoric CLI Reference

### PR DESCRIPTION
**Pull request by ansabgillani**
Add `follow` command reference to doc

### CODE REVIEW

**Review by toliaqat — CHANGES_REQUESTED** [review]
This change has output of `--help`, which might not be ideal content for documentation. The reason is that these options can get change over time. In the documentation, we usually add stuff that is long-lasting and might not have explained in the --help option.

**Comment by ansabgillani** [comment]
https://github.com/Agoric/documentation/pull/1116#pullrequestreview-2097618721
Just followed the conventions here from the rest of the page. Based on our conversation, all good.

**Review by mudassir-agoric — COMMENTED** [review]
Looks good to me!

**Review by Jovonni — APPROVED** [review]
lgtm

**Review by toliaqat — APPROVED** [review]

**Pull request merged**
