### PR TITLE
Move zoe docs over from ERTP

### PR DESCRIPTION
**Pull request by katelynsills**
Feel free to let me know if we need any changes or if these aren't in the right place. Some of these are still in progress but wanted to get them over here pronto.

### CODE REVIEW

**Comment by barbaraliau** [comment]
@katelynsills I know Zoe is technically under ERTP, but would it make sense
to have it under its own namespace e.g. /zoe/guide/?

**Comment by katelynsills** [comment]
That sounds good to me! I'll move the files

**Comment by katelynsills** [comment]
@barbaraliau Moved the files, let me know if this looks right!

**Comment by barbaraliau** [comment]
Perfect. I'm going to merge this in so I can include it in the next update that refactors the navigation.

**Pull request merged**
