### PR TITLE
chore: replace ERTP diagram with class diagram (WIP)

### PR DESCRIPTION
**Pull request by dckc**
- [x] new diagrams
 - [x] edit .md files to include them

### CODE REVIEW

**Comment by amessbee** [comment]
@dckc any specific needed that I can work on to pull it out of draft? Personally, I believe there is some clutter in the new diagram. In particular, some of connections are crossing each other that need not do so. If you agree, I can spend some time to draw one with minimum possible crossings, otherwise, let us merge this.

**Comment by dckc** [comment]
This only has the diagrams. It doesn't change any of the .md files to include them. If you'd like to do that, that would be great.

As to crossings... let's do that in a follow-on PR.

**Comment by amessbee** [comment]
@dckc have a look: [ERTP page in Learn](https://99207438.documentation-7tp.pages.dev/guides/ertp/). Does it work?

**Comment by dckc** [comment]
Yes, this addresses linking the diagrams.

It presents the most complex one first, unfortunately. But we can deal with that in a later edit...

I see lots of stuff I want to change on that page:
 - get rid of quatloos
 - cite thee existing section on ocaps... actually: either drop it or explain how it relates
 - ... and so on

**Comment by amessbee** [comment]
> Yes, this addresses linking the diagrams.
> 
> It presents the most complex one first, unfortunately. But we can deal with that in a later edit...
> 
> I see lots of stuff I want to change on that page:
> 
> * get rid of quatloos
> * cite thee existing section on ocaps... actually: either drop it or explain how it relates
> * ... and so on

Created an issue #1165  - let us address them in a fresh PR?

**Pull request merged**
