### PR TITLE
feat(repl): how to make amounts and payments

### PR DESCRIPTION
**Pull request by 0xpatrickdev**
The purpose of this PR is to add more information to the [**Using the REPL**](https://docs.agoric.com/reference/repl/#using-the-repl) section of the documentation. 

### What was added  
- [x] "Making Amounts and Payments" section in the REPL, with description and code sample
- [x] Local Variable Assignment in the REPL, with code sample
- [x] Two sentences describing "E and harden behavior", in "guides/js-programming/eventual-send" see #679

### CODE REVIEW

**Comment by 0xpatrickdev** [comment]
In draft mode per the contributing guidelines, but ready for feedback & review

**Comment by dckc** [comment]
Contributing guidelines suggest draft for things that are ready for review? I'm not familiar with that. That seems broken.

41469e7 is relevant to #679 , but the REPL stuff is ag-solo / beta stuff that we seem to be moving away from. I wonder about closing this.

**Comment by dckc** [comment]
this looks relevant to #941

**Comment by dckc** [comment]
> ... I wonder about closing this.

hearing no objections, done.

**Pull request closed without merging**
