### PR TITLE
chore: added images to the getting-started guide

### PR DESCRIPTION
**Pull request by tgrecojs**
added images to the getting-started guide indicating what the user should see if successful

related to #652

### CODE REVIEW

**Comment by dckc** [comment]
The images I'm most interested in are the resulting web pages captured in the builde noted in #652 ; for example the fungible faucet dapp and perhaps one or two wallet shots.

Showing the expected text output is useful too, but not in an image; please use text there.

**Comment by tgrecojs** [comment]
> different images, please

updated the guide with screenshots. 

sorry for the mix-up - I saw the command-line images in the nodeeasy gist and followed suit 😬

**Comment by dckc** [comment]
Looks good.

@kennyrowe please take a look? Or @jeetraut ? or @samsiegart ?
https://deploy-preview-683--agoric-docs.netlify.app/documentation/getting-started/start-a-project.html

**Review by dckc — APPROVED** [review]

**Review by samsiegart — CHANGES_REQUESTED** [review]
The "Connect Solo Wallet" may change soon but for the most part looks good. Can we crop these a little neater please though? There's some extra space to the side of the window on most of them.

**Comment by tgrecojs** [comment]
@samsiegart updated the PR so imgs r cropped correctly

**Review by samsiegart — APPROVED** [review]
LGTM

**Pull request merged**
