### PR TITLE
chore: referenced latest video

### PR DESCRIPTION
**Pull request by tgrecojs**
PR for #685

### CODE REVIEW

**Comment by dckc** [comment]
any idea why the deploy preview still shows the old one?
https://deploy-preview-690--agoric-docs.netlify.app/documentation/getting-started/before-using-agoric.html#quick-start

**Review by dckc — CHANGES_REQUESTED** [review]
Ah! we have this video in there twice. Please update the one in `before-using-agoric.md` too.

**Comment by dckc** [comment]
@cboydstun you made another video, right?

**Comment by cboydstun** [comment]
> @cboydstun you made another video, right?

Yes I've got the new video on my personal YouTube [here](https://youtu.be/Yp76WxbaNhQ). I'll poke marketing side about getting it up on official Agoric channels. Also, I can put a voiceover and/or screen text whatever we need.

**Comment by Tyrosine22** [comment]
I'm closing this PR in favor of fixing this issue in PR #816 (https://github.com/Agoric/documentation/pull/816).

**Pull request closed without merging**
