### PR TITLE
Added explainers for dapp-offer-up

### PR DESCRIPTION
**Pull request by kbennett2000**
Added explainers for:
- How to Start a Local Chain 
-- https://github.com/Agoric/documentation/issues/934
-- https://github.com/Agoric/documentation/blob/kbennett2000-patch-1/main/guides/getting-started/explainer-how-to-start-a-local-chain.md

- How to Deploy a Smart Contract 
-- https://github.com/Agoric/documentation/issues/935
-- https://github.com/Agoric/documentation/blob/kbennett2000-patch-1/main/guides/getting-started/explainer-deploying-a-smart-contact.md

- How to Initiate an Offer
-- https://github.com/Agoric/documentation/issues/936
-- https://github.com/Agoric/documentation/blob/kbennett2000-patch-1/main/guides/getting-started/explainer-how-to-make-an-offer.md

How Does Zoe Offer Work
- NOTE: This uses the same explainer page as "How to Initiate an Offer" as both topics are covered
-- https://github.com/Agoric/documentation/issues/937

### CODE REVIEW

**Comment by dckc** [comment]
we've avoided spaces in filenames to date.

The norm for this repo seems to be [kebab-case](https://developer.mozilla.org/en-US/docs/Glossary/Kebab_case)

**Comment by dckc** [comment]
Are these docs in the navigation structure? How does a reader get to them from the docs homepage?

**Comment by kbennett2000** [comment]
> Are these docs in the navigation structure? How does a reader get to them from the docs homepage?

https://miro.com/app/board/uXjVNpwnZ-I=/

**Comment by dckc** [comment]
The [Making an Offer in dapp\-offer\-up](https://www.youtube.com/embed/SbxygFIiXWA) video is good progress, but there are a lot of red squigglies that make it look like something is wrong.

**Comment by dckc** [comment]
> > Are these docs in the navigation structure? How does a reader get to them from the docs homepage?
> 
> https://miro.com/app/board/uXjVNpwnZ-I=/

This PR doesn't seem to reflect the structure in that miro board. Is editing the nav config files happening in some other PR?

https://github.com/Agoric/documentation/blob/main/main/.vuepress/config.js
https://github.com/Agoric/documentation/blob/main/main/.vuepress/themeConfig/nav.js

**Comment by kbennett2000** [comment]
> > > Are these docs in the navigation structure? How does a reader get to them from the docs homepage?
> > 
> > 
> > https://miro.com/app/board/uXjVNpwnZ-I=/
> 
> This PR doesn't seem to reflect the structure in that miro board. Is editing the nav config files happening in some other PR?
> 
> https://github.com/Agoric/documentation/blob/main/main/.vuepress/config.js https://github.com/Agoric/documentation/blob/main/main/.vuepress/themeConfig/nav.js

As per @sufyaankhan's request, I'm building a prototype to show to new nav / doc structure before implementing any vuepress / vitepress changes. 

https://github.com/kbennett2000/agoric-slides/

**Comment by dckc** [comment]
In the Starting a Local Chain video, the voice-over says

> all the configuration for Docker
> is going to live right here in your
> package Json file

https://www.youtube.com/watch?v=WJ1MlHudpuM&t=42s

That doesn't seem quite right. Most of the configuration for docker is in `docker-compose.yml`.

**Comment by dckc** [comment]
@kriskowal is this intended to close 934 etc?

If so, it can help to [make the link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) in such a way that project management tools grok.

**Review by sufyaankhan — APPROVED** [review]

**Review by sufyaankhan — CHANGES_REQUESTED** [review]
Red squigly lines - ah - most probably its just a missing library in Kris's setup.
If Dan could give a few mins to Kris (sometime) he can get that fixed.
I do agree docker config comment noted in the video needs to be changed.
Kris will update the video recording accordingly.

**Review by dckc — DISMISSED** [review]
spaces in filenames just bit me again recently. Let's not go there, at least without wider team discussion.

**Comment by dckc** [comment]
> Red squigly lines - .... If Dan could give a few mins to Kris (sometime) he can get that fixed.

We chatted briefly about using [configure-vscode.sh](https://github.com/Agoric/agoric-sdk/blob/master/scripts/configure-vscode.sh)

any luck, @kbennett2000 ?

**Review by sufyaankhan — APPROVED** [review]

**Review by dckc — CHANGES_REQUESTED** [review]
since these are new pages, they should get added to nav.js and/or config.mjs

**Pull request closed without merging**
