### PR TITLE
questions and feedback

### PR DESCRIPTION
**Pull request by hschoenburg**
I tried running through the guess37 contract. There really is not much to go on here. Maybe Im missing something? The docs desperately need more high level explanations and context. The actual contract example doesnt illustrate much either.

### CODE REVIEW

**Comment by DavidBruant** [comment]
Hi @hschoenburg 
Thank you very much for your feedback!
The documentation in this repo is very much being built with no pretention that it's complete or anywhere near complete

`guess37` really is a starting point and the rest has not been written yet

You can find what is planned in the "planned" column of [this board](https://github.com/Agoric/Documentation/projects/1?fullscreen=true)

I'll take the time to answer your specific comments/questions later

**Comment by hschoenburg** [comment]
Ok great thanks. Let me know how I can be helpful

**Comment by katelynsills** [comment]
@hschoenburg Hi Hans! I know I owe you documentation on Zoe. I hope to get that to you soon.

**Comment by Chris-Hibbert** [comment]
I have a (very) [slightly more fleshed out example](https://github.com/Agoric/Documentation/issues/21) I put together for Dean, mostly to demonstrate that the REPL is usable for experimenting with contracts.

The largest example we have, working within the ContractHost framework is a [second price auction](https://github.com/Agoric/ERTP/pull/103) I wrote. It's close enough to final to be useable for pedagogical purposes.

**Comment by katelynsills** [comment]
Closing as outdated

**Pull request closed without merging**
